# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec7c78f84be24ec1dc7a41789bb19523f23987b289271b0acb1deb26f9703efa64c14401a17c44ecc392277a3166383a1c811641adfe23f1cc17d48abfc1fed1

test:
  secret_key_base: dae669055927c2855a3e6277289403584219413f90ff78b961d67bfab061c7e8cba5dfa53594f78ba491ec2673e2e71b876f7e2e5bf6c400ca1a49ad7a455318

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
